// types: mcq | tf | scenario
export const QUIZZES = [
  {
    id: "phishing-fundamentals",
    title: "Phishing Fundamentals",
    category: "phishing",
    difficulty: "Easy",
    minutes: 5,
    timed: false,
    description: "Can you spot the basic warning signs of a phishing attempt?",
    questions: [
      {
        type: "mcq",
        q: "Which sender address is most likely legitimate for PayPal?",
        options: ["service@paypa1.com", "support@paypal-security.net", "service@paypal.com", "paypal@secure-mail.co"],
        answer: 2,
        explanation: "Only service@paypal.com uses PayPal's real domain. The others use lookalike or unrelated domains — paypa1 swaps an l for a 1, and 'paypal-security.net' is a different domain entirely.",
      },
      {
        type: "tf",
        q: "A padlock icon in the address bar proves a website is safe and legitimate.",
        options: ["True", "False"],
        answer: 1,
        explanation: "False. The padlock only means the connection is encrypted. Phishing sites routinely use HTTPS, so the padlock says nothing about who owns the site.",
      },
      {
        type: "mcq",
        q: "An email says your account will be deleted in 12 hours unless you 'verify' immediately. What is this technique called?",
        options: ["Encryption", "Urgency pressure", "Two-factor authentication", "Spam filtering"],
        answer: 1,
        explanation: "Manufactured urgency short-circuits careful thinking. Legitimate organisations rarely threaten same-day account deletion by email.",
      },
      {
        type: "mcq",
        q: "What is the safest way to check a link in a suspicious email?",
        options: ["Click it quickly and close the page if it looks wrong", "Hover over it (or long-press on mobile) to preview the destination", "Forward the email to a friend to test", "Reply and ask the sender if it's safe"],
        answer: 1,
        explanation: "Previewing the destination without clicking reveals the real URL. Better still, skip the link and navigate to the site directly.",
      },
      {
        type: "tf",
        q: "If an email contains your real name, it must be from a legitimate source.",
        options: ["True", "False"],
        answer: 1,
        explanation: "False. Names are easily harvested from breaches and social media. Spear phishing uses personal details precisely to appear legitimate.",
      },
      {
        type: "scenario",
        q: "SCENARIO: You receive an email from 'IT Helpdesk' saying your mailbox is full. It asks you to log in via the attached HTML file to expand storage. What do you do?",
        options: ["Open the HTML file — it's from IT", "Delete it; mailbox upgrades never need attachments", "Report it as phishing and verify with IT through the official channel", "Forward it to colleagues to warn them"],
        answer: 2,
        explanation: "HTML attachments that present login pages are a classic credential-harvesting trick. Report it and verify with IT directly — forwarding spreads the malicious file.",
      },
    ],
  },
  {
    id: "url-detective",
    title: "URL Detective",
    category: "phishing",
    difficulty: "Medium",
    minutes: 6,
    timed: true,
    timeLimit: 240,
    description: "A timed challenge: dissect real-looking URLs and find the fakes.",
    questions: [
      {
        type: "mcq",
        q: "Which URL actually belongs to GTBank?",
        options: ["https://gtbank.com.ng.account-check.co/login", "https://secure-gtbank.com/login", "https://www.gtbank.com/login", "https://gtbank.verify-portal.net/login"],
        answer: 2,
        explanation: "Read right to left: the registered domain must be gtbank.com. The others belong to account-check.co, secure-gtbank.com, and verify-portal.net.",
      },
      {
        type: "mcq",
        q: "In https://login.microsoft.com.session-verify.io/auth, what is the real domain?",
        options: ["login.microsoft.com", "microsoft.com", "session-verify.io", "auth"],
        answer: 2,
        explanation: "Everything before session-verify.io is a subdomain the attacker created. The registered domain — the part that matters — is session-verify.io.",
      },
      {
        type: "tf",
        q: "A URL using an IP address like http://102.89.33.14/bank is a warning sign for a banking login.",
        options: ["True", "False"],
        answer: 0,
        explanation: "True. Legitimate banks use their branded domains. Raw IP addresses in links are strongly associated with phishing infrastructure.",
      },
      {
        type: "mcq",
        q: "Which character trick is used in 'www.arnazon.com'?",
        options: ["Number substitution", "rn imitating m", "Extra subdomain", "URL shortening"],
        answer: 1,
        explanation: "In many fonts 'rn' is nearly indistinguishable from 'm'. arnazon ≠ amazon. Lookalike characters are a staple of phishing domains.",
      },
      {
        type: "scenario",
        q: "SCENARIO: A WhatsApp message offers a government grant via https://bit.ly/grant-claim. The shortened link 'saves space'. Your move?",
        options: ["Tap it — bit.ly is a trusted company", "Expand/preview the short link first, and verify the grant on the official government site", "Tap it but don't enter any data", "Share it with family in case it's real"],
        answer: 1,
        explanation: "Shorteners hide destinations. Preview the target, and verify grants only on official portals. Even 'just looking' can trigger drive-by downloads on unpatched devices.",
      },
      {
        type: "tf",
        q: "Scammers can buy search-engine ads so their fake site appears above the real one.",
        options: ["True", "False"],
        answer: 0,
        explanation: "True. Malicious ads ('malvertising') routinely impersonate banks and wallets. For sensitive sites, use bookmarks instead of search results.",
      },
    ],
  },
  {
    id: "password-protection",
    title: "Password & Account Protection",
    category: "password",
    difficulty: "Easy",
    minutes: 5,
    timed: false,
    description: "Passphrases, reuse, managers and 2FA — test your account-security instincts.",
    questions: [
      {
        type: "mcq",
        q: "Which password is hardest to crack?",
        options: ["P@ssw0rd2024!", "Chelsea1990", "mango-orbit-violin-snow", "qwerty!@#"],
        answer: 2,
        explanation: "Length wins. Four random words massively outscale short 'complex' passwords, which cracking tools are specifically tuned to guess.",
      },
      {
        type: "tf",
        q: "Reusing one strong password everywhere is safe because it's hard to guess.",
        options: ["True", "False"],
        answer: 1,
        explanation: "False. If any one site is breached, credential-stuffing bots try that password on every other major service within hours.",
      },
      {
        type: "mcq",
        q: "Which 2FA method is most resistant to phishing?",
        options: ["SMS codes", "Email codes", "Hardware security key / passkey", "Security questions"],
        answer: 2,
        explanation: "Hardware keys and passkeys verify the real website cryptographically — a fake site simply can't complete the login. SMS can be SIM-swapped; questions can be researched.",
      },
      {
        type: "mcq",
        q: "You receive a 2FA push prompt you didn't trigger. What does it most likely mean?",
        options: ["A harmless glitch", "Someone has your password and is trying to log in", "Your app needs an update", "Your account was deleted"],
        answer: 1,
        explanation: "An unexpected prompt means your password has been compromised. Deny it and change the password immediately.",
      },
      {
        type: "tf",
        q: "A password manager means you only need to remember one strong master passphrase.",
        options: ["True", "False"],
        answer: 0,
        explanation: "True. The manager generates and stores unique passwords for every site; you protect the vault with one strong passphrase plus 2FA.",
      },
    ],
  },
  {
    id: "social-engineering-defense",
    title: "Social Engineering Defense",
    category: "social-eng",
    difficulty: "Hard",
    minutes: 7,
    timed: false,
    description: "Pretexting, BEC fraud and OTP theft — scenario-heavy and tricky.",
    questions: [
      {
        type: "scenario",
        q: "SCENARIO: 'MD' emails: 'In a confidential meeting, can't call. Pay vendor invoice ₦2.4M before 3pm. Don't loop in finance yet.' Best response?",
        options: ["Pay it — the MD is the boss", "Reply asking for the invoice details", "Verify with the MD by phone/known channel before any action", "Forward to the vendor to confirm"],
        answer: 2,
        explanation: "Authority + urgency + secrecy is the BEC signature. Out-of-band verification on a known number is the only safe move; replying just talks to the attacker.",
      },
      {
        type: "scenario",
        q: "SCENARIO: A caller from 'your bank's fraud desk' says a transfer is being reversed and asks you to read out the code just sent to your phone. The code is real. What's happening?",
        options: ["A standard reversal procedure", "The caller is using your OTP to authorise their own transaction", "A network test by the telco", "A 2FA system error"],
        answer: 1,
        explanation: "The attacker triggered that OTP by initiating a transaction or login. Reading it out completes their attack. Banks never ask you to read OTPs aloud.",
      },
      {
        type: "mcq",
        q: "Why do attackers insist on secrecy ('keep this between us for now')?",
        options: ["Politeness", "It isolates you from people who would spot the scam", "Company policy", "To protect your privacy"],
        answer: 1,
        explanation: "Secrecy disables your strongest defence: a second pair of eyes. Any request that forbids verification is self-incriminating.",
      },
      {
        type: "tf",
        q: "Refusing to give information to an unverified caller and calling back on an official number is considered rude and unprofessional.",
        options: ["True", "False"],
        answer: 1,
        explanation: "False. Verification is standard professional practice. Legitimate callers expect it; only attackers push back against it.",
      },
      {
        type: "scenario",
        q: "SCENARIO: A USB drive labelled 'Salary Review Q3' appears in the office car park. The most secure action is to:",
        options: ["Plug it into an old laptop to check", "Plug it in but don't open files", "Hand it to IT/security without connecting it", "Format it and reuse it"],
        answer: 2,
        explanation: "Baiting drives can attack the moment they're connected — no file-opening required. Curiosity-proof labels are part of the trap.",
      },
      {
        type: "mcq",
        q: "Which detail makes a spear-phishing email more dangerous than mass phishing?",
        options: ["Bad grammar", "Personalised details researched about you and your work", "A generic greeting", "A missing subject line"],
        answer: 1,
        explanation: "Personalisation (your projects, colleagues, role) builds false trust and defeats the 'generic greeting' heuristic entirely.",
      },
    ],
  },
  {
    id: "mobile-messaging-safety",
    title: "Mobile & Messaging Safety",
    category: "mobile",
    difficulty: "Medium",
    minutes: 5,
    timed: false,
    description: "Smishing, app permissions, and Wi-Fi traps for the device that never leaves your hand.",
    questions: [
      {
        type: "mcq",
        q: "A text says: 'Your package is held. Pay ₦950 delivery fee: [link]'. You aren't expecting a package. This is most likely:",
        options: ["A courier system update", "Smishing — SMS phishing", "A wrong number", "A loyalty reward"],
        answer: 1,
        explanation: "Fake delivery-fee texts are among the most common smishing lures. The small amount lowers suspicion; the real prize is your card details.",
      },
      {
        type: "tf",
        q: "An app requesting SMS access could potentially read your banking OTPs.",
        options: ["True", "False"],
        answer: 0,
        explanation: "True. SMS permission grants access to incoming messages, including one-time codes — which is why it should be granted with extreme care.",
      },
      {
        type: "mcq",
        q: "Which network habit is safest for mobile banking in public?",
        options: ["Any open Wi-Fi with a strong signal", "The café's Wi-Fi if staff confirm the name", "Your own mobile data or personal hotspot", "A neighbour's unlocked network"],
        answer: 2,
        explanation: "Your cellular connection avoids rogue hotspots and snooping on shared networks entirely. If you must use public Wi-Fi, add a reputable VPN.",
      },
      {
        type: "scenario",
        q: "SCENARIO: A 'flashlight' app requests contacts, SMS and location at install. Best move?",
        options: ["Accept — apps need permissions to work", "Install but plan to revoke later", "Deny and choose an app whose permissions match its purpose", "Grant only location"],
        answer: 2,
        explanation: "A torch needs the camera flash — nothing else. Permission requests far beyond an app's purpose are a classic sign of data harvesting.",
      },
      {
        type: "tf",
        q: "Sideloading APKs from forums is fine as long as the app has good reviews there.",
        options: ["True", "False"],
        answer: 1,
        explanation: "False. Outside official stores there's no malware screening, and 'reviews' are easily faked. Modified APKs are a top Android infection vector.",
      },
    ],
  },
  {
    id: "cyber-hygiene-checkup",
    title: "Cyber Hygiene Check-up",
    category: "hygiene",
    difficulty: "Easy",
    minutes: 4,
    timed: false,
    description: "Updates, backups, oversharing and incident response — the everyday essentials.",
    questions: [
      {
        type: "mcq",
        q: "The 3-2-1 backup rule means:",
        options: ["3 passwords, 2 emails, 1 phone", "3 copies of data, 2 different media, 1 off-site", "Back up 3 times a day", "3 devices, 2 users, 1 admin"],
        answer: 1,
        explanation: "Three copies on two different types of storage with one kept off-site (or in the cloud) survives theft, fire, and ransomware.",
      },
      {
        type: "tf",
        q: "Software updates are mostly cosmetic and can be postponed indefinitely.",
        options: ["True", "False"],
        answer: 1,
        explanation: "False. Many updates patch security holes that attackers are actively exploiting. Postponing updates keeps known doors open.",
      },
      {
        type: "mcq",
        q: "You realise you just entered your password on a fake login page. The FIRST thing to do is:",
        options: ["Wait and see if anything happens", "Change that password immediately (and anywhere it's reused)", "Delete your browser history", "Buy a new laptop"],
        answer: 1,
        explanation: "Stolen credentials are used within minutes by automated systems. Changing the password fast — plus enabling 2FA — closes the window.",
      },
      {
        type: "scenario",
        q: "SCENARIO: A quiz going around asks your first pet, first school, and mother's maiden name for a 'fun nickname'. Why is this risky?",
        options: ["It wastes time", "Those are common security-question answers", "It uses too much data", "Quizzes can't be risky"],
        answer: 1,
        explanation: "These viral quizzes harvest exactly the answers used to reset passwords and pass identity checks. Treat security answers like passwords.",
      },
      {
        type: "tf",
        q: "Reporting a phishing email you clicked is worse than staying quiet, because you'll get in trouble.",
        options: ["True", "False"],
        answer: 1,
        explanation: "False. Fast reporting is the most valuable response — it lets security teams contain damage. Silence is what turns a mistake into a breach.",
      },
    ],
  },
];
